web:
   image: web
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "81:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb:10.8.2
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"

phpmyadmin:
  image: phpmyadmin
  links:
    - db
  ports:
    - 8890:80
  environment:
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: database
